### ISSUE TITLE
Not an issue! Just a request. 

### ISSUE THREAD

**Issue by MalwareMakers** [safesploit/PythonRAT#13]
Hi, I was wondering if you would be interested in doing a collab. Here's one of my software's: [here](https://github.com/MalwareMakers/HarBringer-V2).

**Comment by safesploit** [comment]
@MalwareMakers cool stuff! Sure I'd be interested, HarBringer V2 looks like it was fun to develop. 
PythonRAT is open-source, the thing I ask is that it's used for education purposes and not malicious. This factor is largely why I won't rewrite the backdoor/client into a lower-level language like C.

**Comment by MalwareMakers** [comment]
@safesploit Sure I have no problems with education only, I don't really want to create a fully undetectable or complete backdoor with every possible function, also Harbringer-V2 isn't fud and besides u still need to configure it correctly to bypass most av's, none of which i have mentioned in the actual readme file. I understand the need to make sure this kind of stuff isn't made to be completely a) powerful and B) usable by those who don't have the right skill sets.
