### ISSUE TITLE
does not work on windows machine

### ISSUE THREAD

**Issue by ethicalhacker7192** [safesploit/PythonRAT#2]
every time i try executing it on windows it keeps saying can not run on machine because it is outdated.

**Comment by safesploit** [comment]
Python 2.7 is an EOL version, which only supported up to Windows 7.
My logic behind using Python 2.7 is that it was the latest version which supported Windows XP.

You should be able to use a newer revision of Python but at the risk of not having a wide range of OS support (unless you compile under different versions of Python).
  * backdoor_WinXP-7.exe
  * backdoor_Win7-11.exe
 

I attempted the logic of _compile once_. But it isn't perfect!
Look at [C Keylogger](https://github.com/safesploit/C_keylogger), as C compiles to machine code (not byte-code) and, therefore, must have architecture considered.
