### ISSUE TITLE
When executing script I have following errors: mss missing, json missing

### ISSUE THREAD

**Issue by rickyzg** [safesploit/PythonRAT#6]
I have following errors: mss missing, json missing when executing script. I have installed Python 3.10.11, Pip 23.1.2, Pyinstaller latest, added paths, what could be a issue?

**Comment by safesploit** [comment]
I presume the script you're referring to is `backdoor.py`?
If so did you also install the [dependencies](https://github.com/safesploit/PythonRAT#dependencies)?


```
pip install mss \
            pynput \
            requests
```

**Comment by rickyzg** [comment]
> I presume the script you're referring to is `backdoor.py`? If so did you also install the [dependencies](https://github.com/safesploit/PythonRAT#dependencies)?
> 
> ```
> pip install mss \
>             pynput \
>             requests
> ```

Yes, I installed it on Win 10, and I am doing it all from Windows 10, maybe that is the problem, is this only for Linux?

**Comment by rickyzg** [comment]
I used pyinstaller to create exe file, also I have changed s,connect in the script but when executing it, it gives me that errors.

**Comment by rickyzg** [comment]
So I fixed it by changing module versions in the backdoor.py script and changing sock.bind in c2.py

**Comment by rickyzg** [comment]
> I presume the script you're referring to is `backdoor.py`? If so did you also install the [dependencies](https://github.com/safesploit/PythonRAT#dependencies)?
> 
> ```
> pip install mss \
>             pynput \
>             requests
> ```

It is working now if I convert directly from backdoor.py to .exe, the only problem I have is when I encrypt the same backdoor.py with pycrypt then it is not working, gives me errors.

**Comment by safesploit** [comment]
For my purposes, which are shown in the [README.md](https://github.com/safesploit/PythonRAT/blob/main/README.md) I ran `c2.py` within Kali Linux and `backdoor.py` in a Windows 10. However, the backdoor as a Python script does run in any environment.

**Comment by rickyzg** [comment]
Thanks, I will just use it without using pycrypt
